FROM ruby:2.6.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN mkdir /app
WORKDIR /app

ADD Gemfile /app/Gemfile
RUN gem install bundler

RUN apt-get update -qq && \
  apt-get install -y build-essential \
  libpq-dev 

RUN bundle install

ADD . /app
